### PR TITLE
modernize

### LINKED ISSUE #1: add ability to set Piwik tracking code in footer of Github issues mirror
In the config.php file, maybe we could add a new define to let us add the Piwik tracking code in the footer of all pages on issues.piwik.org?

Here is the code to would be added to our instance at [issues.piwik.org](http://issues.piwik.org)

```
<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u=(("https:" == document.location.protocol) ? "https" : "http") + "://demo.piwik.org/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', 44]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0]; g.type='text/javascript';
    g.defer=true; g.async=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<noscript><p><img src="http://demo.piwik.org/piwik.php?idsite=44" style="border:0;" alt="" /></p></noscript>
<!-- End Piwik Code -->
```

### LINKED ISSUE #5: ability to blacklist certain types of files (eg. swf)
The goal of this issue is to add a blacklist of filetypes, that should not be mirrored in the github issues mirror. We could set the default blacklist to `swf` to exclude flash files from being synched.

Why? this is a security improvement. We received this report:

```
Hello.
I am to founded xss in subdomain of piwik.org
http://issues.piwik.org/attachments/1199/swelen_dateslider.swf?instance=alert(document.domain))}catch(e){}//
with best regards,
Sergey Markov
```

blacklisting some file types would help minimise such XSS vulnerability.

### LINKED ISSUE #8: Add CLI Command for system-check
I vote for a CLI-Command to check if everything is running fine with PIWIK! I recently I accidently noticed that for some reason the Directory and MySQL-Permissions for Piwik where both screwed and PIWIK was NOT RUNNING for about one month and loosing trackings about that!!! Horrible!

I vote for some CLI-Command that is able to give some output for different important checks, that f.e. can be processed by MONIT or some other monitoring solutions to keep an eye on such horrible problems.

### PR DESCRIPTION
**Pull request by Findus23**
While going through the code for #9 I noticed that some dependencies are outdated.

I made those changes:
- fixed #8 
- updated parsedown to the latest version and replaced php-markdown with parsedown
- update PHPMailer
- update to Slim 3 (and Twig), which simplified a bit of code as it supports some of the features that needed extensions out of the box.
- update github-api (and guzzle). It now uses php-cache, so any cache from [this list](http://www.php-cache.com/en/latest/) can be used.
- new (but similar) design with bootstrap 4
- better markdown rendering (closer to how github displays it)
- fixes #5 (disallow unsafe extentions)
- fixes #1 (allow piwik tracking)
- sort issues by recently updated
- add logging

Everything seems to work, but I'll need to do more testing and more cleanup.

### CODE REVIEW

**Comment by Findus23** [comment]
I have uploaded my version on my server, so you can compare the changes:
https://issues.lw1.at/

A small benchmark shows that the speed didn't really change:

```diff
1c1
< ➜  ~ ab -n 20 https://issues.lw1.at/8392
---
> ➜  ~ ab -n 20 https://issues.piwik.org/8392
6c6
< Benchmarking issues.lw1.at (be patient).....done
---
> Benchmarking issues.piwik.org (be patient).....done
9,10c9,10
< Server Software:        nginx/1.13.3
< Server Hostname:        issues.lw1.at
---
> Server Software:        Apache/2.2
> Server Hostname:        issues.piwik.org
12,13c12,13
< SSL/TLS Protocol:       TLSv1.2,ECDHE-RSA-AES256-GCM-SHA384,2048,256
< TLS Server Name:        issues.lw1.at
---
> SSL/TLS Protocol:       TLSv1.2,ECDHE-RSA-AES128-GCM-SHA256,2048,128
> TLS Server Name:        issues.piwik.org
16c16
< Document Length:        36974 bytes
---
> Document Length:        22346 bytes
19c19
< Time taken for tests:   5.711 seconds
---
> Time taken for tests:   6.520 seconds
22,27c22,27
< Total transferred:      744040 bytes
< HTML transferred:       739480 bytes
< Requests per second:    3.50 [#/sec] (mean)
< Time per request:       285.534 [ms] (mean)
< Time per request:       285.534 [ms] (mean, across all concurrent requests)
< Transfer rate:          127.24 [Kbytes/sec] received
---
> Total transferred:      450140 bytes
> HTML transferred:       446920 bytes
> Requests per second:    3.07 [#/sec] (mean)
> Time per request:       325.987 [ms] (mean)
> Time per request:       325.987 [ms] (mean, across all concurrent requests)
> Transfer rate:          67.42 [Kbytes/sec] received
31,34c31,34
< Connect:       80  106  59.0     83     279
< Processing:   138  179  47.3    169     295
< Waiting:      128  159  30.5    159     267
< Total:        220  285  98.7    256     574
---
> Connect:       96  100   1.7    100     104
> Processing:   138  226  67.4    214     378
> Waiting:      102  190  67.7    179     343
> Total:        237  326  67.8    315     479
37,45c37,45
<   50%    256
<   66%    259
<   75%    269
<   80%    349
<   90%    528
<   95%    574
<   98%    574
<   99%    574
<  100%    574 (longest request)
---
>   50%    315
>   66%    359
>   75%    375
>   80%    377
>   90%    441
>   95%    479
>   98%    479
>   99%    479
>  100%    479 (longest request)
```

**Comment by mattab** [comment]
@Findus23 Great to see your work on this project. When you're ready to deploy this ping me and we can make it happen :+1:

**Comment by Findus23** [comment]
Thanks, tomorrow I’ll look over the changes again, so this should soon be ready to merge. 

Any more wishes while I am working on it?

I think you’ll need to put html before htm as otherwise i think it gets partially matched. 
https://regex101.com/r/O4M8h5/1

**Comment by mattab** [comment]
Another couple feature requests in case it's do-able: 

* Make all URLs to piwik.org or *piwik.org or *innocraft.cloud *innocraft.com clickable links.  (matching `http[s]://domain*`)

* On homepage, sort all issues by most recently updated so it surfaces the active issues

**Comment by Findus23** [comment]
> Make all URLs to piwik.org or *piwik.org or *innocraft.cloud *innocraft.com clickable links. (matching http[s]://domain*)

Seems like I already fixed that. The new Markdown parser is more Github-like and automatically links all URLs in the text. (and i think `href` was disallowed in HTMLPurifier)
See e.g. https://issues.piwik.org/11184 and https://issues.lw1.at/11184 

> On homepage, sort all issues by most recently updated so it surfaces the active issues

That was an easy change (https://github.com/piwik/github-issues-mirror/pull/10/commits/067abc9aba1d553ff82a2d33a661704b35a4cd99), but it means that we need to delete all data in /data/pages/

**Comment by Findus23** [comment]
It now even works in IE 11

**Comment by mattab** [comment]
Awesome @Findus23 

Deployed it on issues.piwik.org

Had to run the following commands:
```
  wget https://nodejs.org/dist/v6.11.2/node-v6.11.2-linux-x64.tar.gz --no-check-certificate
  tar -xzvf node-v6.11.2-linux-x64.tar.gz 
  echo "export PATH=\$PATH:~/node-v6.11.2-linux-x64/bin" >> $HOME/.bashrc
```

**Pull request merged**
